MallPro/Controllers/MallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MallPro.Models;
using static MallPro.Models.ViewModel;

namespace MallPro.Controllers
{
    public class MallController : Controller
    {
        MallManagementEntities1 db = new MallManagementEntities1();


        public ActionResult DetailsAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DetailsAdd(MallOwnerViewModel DetailsPost)
        {
            if (ModelState.IsValid)
            {
                MallOwnerDetailsTbl NewAdd = new MallOwnerDetailsTbl();
                NewAdd.MallOwnerID = DetailsPost.MallOwnerID;
                NewAdd.OwnerName = DetailsPost.OwnerName;
                NewAdd.Address = DetailsPost.Address;
                NewAdd.Email = DetailsPost.Email;

                db.MallOwnerDetailsTbls.Add(NewAdd);
                db.SaveChanges();
                return RedirectToAction("DetailsAdd");
            }
            return View(DetailsPost);

        }
    




        /*    public ActionResult Category()
            {
                var Category = db.CategoryTbls.FirstOrDefault();
                CategoryViewModel Showcategory = new CategoryViewModel();
                //  Showcategory.CategoryID = Category.CategoryID;
                //  Showcategory.CategoryType = Category.CategoryType;
                return View(Showcategory);

            }

            public ActionResult Index()
            {
                return View();
            }*/
    }
}

MallPro/Views/Mall/DetailsAdd.cshtml
@model MallPro.Models.ViewModel.MallOwnerViewModel
@{
    ViewBag.Title = "DetailsAdd";
}

@using (Html.BeginForm("DetailsAdd", "Mall", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create New Account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(m => m.MallOwnerID, new { @class = "col-md-2 control-label" })
        <div class="col-xs-12 col-md-5">
         @Html.TextBoxFor(m => m.MallOwnerID, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.OwnerName, new { @class = "col-md-2 control-label" })
        <div class="col-xs-12 col-md-5">
            @Html.TextBoxFor(m => m.OwnerName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-xs-12 col-md-5">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-xs-12 col-md-5">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>


    <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
            <span class="sr-only">40% Complete (success)</span>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}